workflows:
  ios-build:
    name: iOS Build
    instance_type: mac_mini_m2

    environment:
      xcode: latest

    scripts:
      - name: Build iOS app
        script: |
          xcodebuild \
            -project Speedometer.xcodeproj \
            -scheme Speedometer \
            -sdk iphoneos \
            -configuration Release \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            build

    artifacts:
      - /tmp/xcodebuild_logs/*.log
